name: Deploy Code

on:
  push:
    branches:
      - main 

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
      
      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  install-dependencies:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
      
      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install dependencies
        run: yarn install --immutable

  build:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
      
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      
      - name: Build TypeScript
        run: yarn build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/

  prepare-deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: dist/
      
      - name: Create .env file
        run: |
          echo -e "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}\nNODE_ENV=production\nDATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
      
      - name: Create deployment package
        run: |
          zip -r deploy.zip \
          discloud.config \
          dist \
          drizzle.config.js \
          .env \
          package.json \
          static \
          yarn.lock
      
      - name: Upload deployment package
        uses: actions/upload-artifact@v3
        with:
          name: deployment-package
          path: deploy.zip

  deploy:
    needs: prepare-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v3
        with:
          name: deployment-package
      
      - name: Deploy to API
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
            -F "file=@deploy.zip" \
            "${{ secrets.API_URL }}")
          if [ "$RESPONSE" -ne 200 ]; then
            echo "::error::Deployment failed with status $RESPONSE"
            exit 1
          fi
